name: News Update

on:
  schedule:
    - cron: "0 21 * * *"  
  workflow_dispatch:    

jobs:
  news-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r server/requirements.txt

      - name: News Update
        working-directory: server/services/
        env:
          DB_STRING: ${{ secrets.DB_STRING }}          
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}  
          NEWS_API_URL: ${{ secrets.NEWS_API_URL }}
        run: python fetch_news.py